before_install:
 - chmod +x gradlew
 
before_script:
 - chmod +x gradlew

language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk7
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
 - .travis/coverage.sh
 - .travis/deploy.sh
